# Generated by Django 5.0 on 2023-12-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myband', '0005_auto_20231231_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
